table Sales_2024
	lineageTag: 83688199-64f8-49b4-b331-241f9c5a9820

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: e6e5dd52-0b06-40c2-a299-d437090aae8d
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24fbbad1-5b0b-4bab-8c96-fa23d2f76e6d
		summarizeBy: none
		sourceColumn: OrderDate

		variation 변형
			isDefault
			relationship: a90c3694-8e18-4691-a75f-d0b51f11879e
			defaultHierarchy: LocalDateTable_0cdec44e-4205-4378-9ee8-8ba2633ba5ef.'날짜 계층'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		lineageTag: 2d7bd42d-1cec-4ae7-827b-1faef83b3e41
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: a719a810-fca1-4b1c-82bb-338cc686098f
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: bd35c8dc-594f-4588-9b5b-63783aa4a4a5
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column '사용자 지정'
		dataType: string
		lineageTag: c9beec61-db0b-4d46-81f1-c5d92fc3591e
		summarizeBy: none
		sourceColumn: 사용자 지정

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: string
		lineageTag: b44b15ab-a45c-4bbc-8333-1a9b0bfa82b9
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: f906697f-76bd-425a-9f3d-74d1e84ad768
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 24a7d3bd-e0f0-49b7-bd3a-87623971add5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: double
		lineageTag: b3aceef7-9651-4461-a64f-54ef8329d5c7
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPrice
		dataType: int64
		formatString: 0
		lineageTag: a12ca3e7-5782-4ec1-a6c3-d939ca8f6287
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: 53fb1910-0d91-4aa3-80bb-fbde6a2e292e
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: a44b4e3d-7f56-407d-b71a-869ac8c8ba38
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: 58397482-6b45-48d1-a61a-2f97df61d7e4
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: f72042d4-8fa8-4615-b2f8-251aca97987e
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column ZipCode
		dataType: string
		lineageTag: 02aceed6-a0ca-43d2-9f5c-37e4103b0c7f
		summarizeBy: none
		sourceColumn: ZipCode

		annotation SummarizationSetBy = Automatic

	column Remark
		dataType: string
		lineageTag: d79e71f6-94be-4e02-9a3d-03ee821d0872
		summarizeBy: none
		sourceColumn: Remark

		annotation SummarizationSetBy = Automatic

	column ZipCode2
		dataType: string
		lineageTag: b8e9c003-ec3d-4e54-9e6d-414314c8a3ff
		summarizeBy: none
		sourceColumn: ZipCode2

		annotation SummarizationSetBy = Automatic

	partition Sales_2024 = m
		mode: import
		source =
				let
				    원본 = Csv.Document(File.Contents("C:\Users\82103\Downloads\Sales_2024.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"승격된 헤더" = Table.PromoteHeaders(원본, [PromoteAllScalars=true]),
				    #"변경된 유형" = Table.TransformColumnTypes(#"승격된 헤더",{{"OrderID", Int64.Type}, {"OrderDate", type text}, {"CustomerID", type text}, {"CustomerName", type text}, {"Region", type text}, {"ProductCode", type text}, {"ProductName", type text}, {"Category", type text}, {"Qty", Int64.Type}, {"UnitPrice", Int64.Type}, {"Sales", Int64.Type}, {"Status", type text}, {"Manager", type text}, {"Phone", type text}, {"ZipCode", Int64.Type}, {"Remark", type text}}),
				    #"OrderID 중복 항목 제거(5행)" = Table.Distinct(#"변경된 유형", {"OrderID"}),
				    #"날짜 이상치 -> Error" = Table.TransformColumnTypes(#"OrderID 중복 항목 제거(5행)",{{"OrderDate", type date}}),
				    #"날짜 이상치 제거" = Table.RemoveRowsWithErrors(#"날짜 이상치 -> Error", {"OrderDate"}),
				    #"CustomerName의 Unknown -> NULL" = Table.ReplaceValue(#"날짜 이상치 제거","Unknown","NULL",Replacer.ReplaceText,{"CustomerName"}),
				    #"CustomerName의 Test User -> NULL" = Table.ReplaceValue(#"CustomerName의 Unknown -> NULL","Test User","NULL",Replacer.ReplaceText,{"CustomerName"}),
				    #"Region -> 서울명으로 변경" = Table.AddColumn(#"CustomerName의 Test User -> NULL", "사용자 지정", each if [Region] = "서울시" then "서울" else if [Region] = "SEOUL" then "서울" else if [Region] = "seoul" then "서울" else null),
				    #"Region -> 서울명으로 변경 후 정렬" = Table.ReorderColumns(#"Region -> 서울명으로 변경",{"OrderID", "OrderDate", "CustomerID", "CustomerName", "Region", "사용자 지정", "ProductCode", "ProductName", "Category", "Qty", "UnitPrice", "Sales", "Status", "Manager", "Phone", "ZipCode", "Remark"}),
				    #"Qty의 null -> 0" = Table.ReplaceValue(#"Region -> 서울명으로 변경 후 정렬",null,0,Replacer.ReplaceValue,{"Qty"}),
				    #"Sales의 이상치 제거" = Table.SelectRows(#"Qty의 null -> 0", each [Sales] > 0 and [Sales] < 100000),
				    #"Status의 Unknown → null" = Table.ReplaceValue(#"Sales의 이상치 제거","Unknown",null,Replacer.ReplaceValue,{"Status"}),
				    #"""-"" 로 전화번호 분리" = Table.SplitColumn(#"Status의 Unknown → null", "Phone", Splitter.SplitTextByDelimiter("-", QuoteStyle.None), {"Phone.1", "Phone.2", "Phone.3"}),
				    #"다시 Phone로 열 병합" = Table.CombineColumns(#"""-"" 로 전화번호 분리",{"Phone.1", "Phone.2", "Phone.3"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Phone"),
				    #"변경된 유형1" = Table.TransformColumnTypes(#"다시 Phone로 열 병합",{{"ZipCode", type text}}),
				    #"추가된 사용자 지정 항목" = Table.AddColumn(#"변경된 유형1", "ZipCode2", each Text.PadStart(Text.From([ZipCode]), 5, "0"))
				in
				    #"추가된 사용자 지정 항목"

	annotation PBI_NavigationStepName = 탐색

	annotation PBI_ResultType = Table

