table '전처리 실습'
	lineageTag: 177b46cc-93fb-4789-8255-a075c4f21f36

	column 인덱스
		dataType: int64
		formatString: 0
		lineageTag: f9aee365-902d-406d-96d9-0bb549c155fb
		summarizeBy: sum
		sourceColumn: 인덱스

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 519644f0-a329-4992-a8b6-68fd0f90aed5
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f7b7398d-fdbd-4791-a668-495501cb7e46
		summarizeBy: none
		sourceColumn: OrderDate

		variation 변형
			isDefault
			relationship: 1a3840f0-cd6a-40e4-8e2a-288b9d86a2e5
			defaultHierarchy: LocalDateTable_c0c9c0a1-1d9b-482d-a43f-71210d8b5ebe.'날짜 계층'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		lineageTag: 6b67fe50-acc9-4e4d-a29c-93e14089f653
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: d345d07a-1d34-48cc-ac97-de97e8692c0d
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f555e689-195a-4eeb-82ef-055642ed6f18
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: string
		lineageTag: 6b84ad80-2a66-4188-8f01-fbcdc2ef98ef
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 8f78e1c3-6251-435f-aa51-c003833b42bd
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8f743b9d-d64c-4bab-a0b3-a2e3840f1d99
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: int64
		formatString: 0
		lineageTag: 23d69a60-c3ac-415e-8dc5-ce5987a35264
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: 3d973d0c-f83e-43c2-9ef0-4661484ce65c
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: string
		lineageTag: e5d1baea-2afb-428e-b345-faed760f7608
		summarizeBy: none
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column level
		dataType: string
		lineageTag: 0784576a-8c06-4c1c-88b8-29a1af692725
		summarizeBy: none
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0ce9eb85-5c2d-4e77-a27b-1ebcc81031d0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: c1a87798-57b9-49a0-aed9-00d4797f9118
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 85d86aa2-f8e4-4ef0-98b4-2bab332d6b0d
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column ZipCode
		dataType: string
		lineageTag: ca3c8106-bfb2-4d89-9b93-b3a335d5300e
		summarizeBy: none
		sourceColumn: ZipCode

		annotation SummarizationSetBy = Automatic

	column ZipCode2
		dataType: string
		lineageTag: e0308f95-a933-406f-8e77-f2aeed8c1256
		summarizeBy: none
		sourceColumn: ZipCode2

		annotation SummarizationSetBy = Automatic

	partition '전처리 실습' = m
		mode: import
		source =
				let
				    원본 = Csv.Document(File.Contents("C:\Users\82103\Downloads\Sales_2024.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"승격된 헤더" = Table.PromoteHeaders(원본, [PromoteAllScalars=true]),
				    #"변경된 유형" = Table.TransformColumnTypes(#"승격된 헤더",{{"OrderID", Int64.Type}, {"OrderDate", type text}, {"CustomerID", type text}, {"CustomerName", type text}, {"Region", type text}, {"ProductCode", type text}, {"ProductName", type text}, {"Category", type text}, {"Qty", Int64.Type}, {"UnitPrice", Int64.Type}, {"Sales", Int64.Type}, {"Status", type text}, {"Manager", type text}, {"Phone", type text}, {"ZipCode", Int64.Type}, {"Remark", type text}}),
				    #"제거된 중복 항목 수" = Table.Distinct(#"변경된 유형", {"OrderID"}),
				    #"변경된 유형1" = Table.TransformColumnTypes(#"제거된 중복 항목 수",{{"OrderDate", type date}}),
				    #"제거된 오류 수" = Table.RemoveRowsWithErrors(#"변경된 유형1", {"OrderDate"}),
				    #"testuser 필터링" = Table.SelectRows(#"제거된 오류 수", each ([CustomerName] <> "Test User")),
				    #"Region 서울시 -> 서울" = Table.ReplaceValue(#"testuser 필터링","서울시","서울",Replacer.ReplaceText,{"Region"}),
				    #"Region SEOUL -> 서울" = Table.ReplaceValue(#"Region 서울시 -> 서울","SEOUL","서울",Replacer.ReplaceText,{"Region"}),
				    #"Region seoul -> 서울" = Table.ReplaceValue(#"Region SEOUL -> 서울","seoul","서울",Replacer.ReplaceText,{"Region"}),
				    #"Sales 이상치 제거" = Table.SelectRows(#"Region seoul -> 서울", each [Sales] >= 0 and [Sales] <= 100000),
				    #"Status Unknown -> null" = Table.ReplaceValue(#"Sales 이상치 제거","Unknown",null,Replacer.ReplaceValue,{"Status"}),
				    #"Phone -> 3개로 열분할" = Table.SplitColumn(#"Status Unknown -> null", "Phone", Splitter.SplitTextByDelimiter("-", QuoteStyle.None), {"Phone.1", "Phone.2", "Phone.3"}),
				    #"다시 Phone 병합" = Table.CombineColumns(#"Phone -> 3개로 열분할",{"Phone.1", "Phone.2", "Phone.3"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Phone"),
				    #"변경된 유형2" = Table.TransformColumnTypes(#"다시 Phone 병합",{{"ZipCode", type text}}),
				    #"추가된 사용자 지정 항목" = Table.AddColumn(#"변경된 유형2", "ZipCode2", each Text.PadStart(Text.From([ZipCode]), 5, "0")),
				    #"다시 정렬한 열 수" = Table.ReorderColumns(#"추가된 사용자 지정 항목",{"OrderID", "OrderDate", "CustomerID", "CustomerName", "Region", "ProductCode", "ProductName", "Category", "Qty", "UnitPrice", "Sales", "Status", "Manager", "Phone", "ZipCode", "ZipCode2", "Remark"}),
				    #"제거된 열 수" = Table.RemoveColumns(#"다시 정렬한 열 수",{"Remark"}),
				    #"추가된 인덱스" = Table.AddIndexColumn(#"제거된 열 수", "인덱스", 1, 1, Int64.Type),
				    #"다시 정렬한 열 수1" = Table.ReorderColumns(#"추가된 인덱스",{"인덱스", "OrderID", "OrderDate", "CustomerID", "CustomerName", "Region", "ProductCode", "ProductName", "Category", "UnitPrice", "Qty", "Sales", "Status", "Manager", "Phone", "ZipCode", "ZipCode2"}),
				    #"추가된 사용자 지정 항목1" = Table.AddColumn(#"다시 정렬한 열 수1", "Sales2", each [UnitPrice] * [Qty]),
				    #"다시 정렬한 열 수2" = Table.ReorderColumns(#"추가된 사용자 지정 항목1",{"인덱스", "OrderID", "OrderDate", "CustomerID", "CustomerName", "Region", "ProductCode", "ProductName", "Category", "UnitPrice", "Qty", "Sales", "Sales2", "Status", "Manager", "Phone", "ZipCode", "ZipCode2"}),
				    #"제거된 열 수1" = Table.RemoveColumns(#"다시 정렬한 열 수2",{"Sales"}),
				    #"이름을 바꾼 열 수" = Table.RenameColumns(#"제거된 열 수1",{{"Sales2", "Sales"}}),
				    #"조건 열이 추가됨" = Table.AddColumn(#"이름을 바꾼 열 수", "level", each if [Sales] > 5000 then "VIP" else "일반"),
				    #"다시 정렬한 열 수3" = Table.ReorderColumns(#"조건 열이 추가됨",{"인덱스", "OrderID", "OrderDate", "CustomerID", "CustomerName", "Region", "ProductCode", "ProductName", "Category", "UnitPrice", "Qty", "Sales", "level", "Status", "Manager", "Phone", "ZipCode", "ZipCode2"}),
				    #"추가된 사용자 지정 열" = Table.AddColumn(#"다시 정렬한 열 수3", "사용자 지정", each Text.Combine({Text.Start([CustomerName], 1), "xx"}), type text),
				    #"다시 정렬한 열 수4" = Table.ReorderColumns(#"추가된 사용자 지정 열",{"인덱스", "OrderID", "OrderDate", "CustomerID", "CustomerName", "사용자 지정", "Region", "ProductCode", "ProductName", "Category", "UnitPrice", "Qty", "Sales", "level", "Status", "Manager", "Phone", "ZipCode", "ZipCode2"}),
				    #"제거된 열 수2" = Table.RemoveColumns(#"다시 정렬한 열 수4",{"CustomerName"}),
				    #"이름을 바꾼 열 수1" = Table.RenameColumns(#"제거된 열 수2",{{"사용자 지정", "CustomerName"}}),
				    #"필터링된 행" = Table.SelectRows(#"이름을 바꾼 열 수1", each [Sales] > x)
				in
				    #"필터링된 행"

	annotation PBI_NavigationStepName = 탐색

	annotation PBI_ResultType = Table

